import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/style/globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import MasterLayout from '@/components/MasterLayout/MasterLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* shadcn Tehem is configured here */}
      <ThemeProvider
            attribute="class"
            defaultTheme="day"
            enableSystem
            disableTransitionOnChange
          >
            <MasterLayout>
              {children}
            </MasterLayout>
            
          </ThemeProvider>
        
        
        </body>
    </html>
  )
}
